version: "2"
services:

  consul:
    image: progrium/consul
    command: -server -bootstrap -ui-dir /ui
    container_name: consul
    ports:
      - 8500:8500
      - 53:53
      - 53:53/udp
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8400:8400
