version: "2"
services:

  cadvisor:
    image: google/cadvisor
    networks:
      monitoring:
        aliases:
          - cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

  prometheus:
    image: angeldimitrov/prometheus-swarm-dns-cadvisor
    ports:
      - "9090:9090"
    networks:
      monitoring:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"

networks:
  monitoring:
    driver: overlay
